"""signup form

Revision ID: ffbeca431011
Revises: b2d8c24e8568
Create Date: 2019-12-04 07:47:01.808419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbeca431011'
down_revision = 'b2d8c24e8568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('signed_up', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_email'), 'subscriber', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_email'), table_name='subscriber')
    op.drop_table('subscriber')
    # ### end Alembic commands ###
